# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-11 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='problemset',
            field=models.ManyToManyField(blank=True, to='contest.ContestProblems'),
        ),
    ]
