# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-24 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_auto_20160424_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestsolution',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.Contest'),
        ),
    ]
