# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-26 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_auto_20160424_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='ignore_flag',
        ),
        migrations.AddField(
            model_name='contest',
            name='rank_list',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='rank_list_1hr_stop',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='rank_list_cache_time',
            field=models.IntegerField(default=0),
        ),
    ]
