# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-04 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_auto_20160426_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='referees',
        ),
        migrations.AddField(
            model_name='contest',
            name='referees',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
