# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-04 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_auto_20160504_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.Contest'),
        ),
    ]
