# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-05 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_faq_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer_referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_referees', to='account.User'),
        ),
    ]
