# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_perference_language'),
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TdmakerQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_status', models.SmallIntegerField(default=0)),
                ('flag', models.SmallIntegerField(default=0)),
                ('memused', models.IntegerField(default=0)),
                ('timeused', models.IntegerField(default=0)),
                ('lang', models.CharField(blank=True, max_length=20, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.User')),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='problem.Problem')),
            ],
        ),
    ]
