# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-11 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20160309_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='classify',
        ),
    ]
