# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_title', models.CharField(blank=True, max_length=255, null=True)),
                ('web_keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('web_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('web_version', models.CharField(blank=True, max_length=50, null=True)),
                ('web_fixing', models.BooleanField(default=False)),
                ('web_stop_judging', models.BooleanField(default=False)),
                ('smtp_server', models.CharField(blank=True, max_length=50, null=True)),
                ('smtp_user', models.CharField(blank=True, max_length=50, null=True)),
                ('smtp_pwd', models.CharField(blank=True, max_length=50, null=True)),
                ('smtp_mail_from', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.SmallIntegerField(default=2015)),
                ('term', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
