# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-12 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnuzoj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='web_notice',
            field=models.TextField(blank=True, default=b'', null=True),
        ),
    ]
