# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-18 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnuzoj', '0002_setting_web_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='web_login_black_list',
            field=models.TextField(blank=True, default=b'all', null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='web_login_limit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='setting',
            name='web_login_white_list',
            field=models.TextField(blank=True, default=b'all', null=True),
        ),
    ]
