# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-09 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnuzoj', '0004_auto_20160518_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='web_register',
            field=models.BooleanField(default=False),
        ),
    ]
