# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-13 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnuzoj', '0005_setting_web_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='web_pwd_equal_username',
            field=models.BooleanField(default=False),
        ),
    ]
