# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-19 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contest', '0008_auto_20160505_1044'),
        ('problem', '0005_problem_classify'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestCodeAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levenshtein_similarity_ratio', models.FloatField(default=0)),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.Contest')),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='problem.Problem')),
                ('status1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status1', to='problem.JudgeStatus')),
                ('status2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status2', to='problem.JudgeStatus')),
            ],
        ),
    ]
