# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursechoosing',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='coursechoosing',
            name='role',
        ),
        migrations.RemoveField(
            model_name='coursechoosing',
            name='start_time',
        ),
        migrations.AddField(
            model_name='coursechoosing',
            name='term',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='coursechoosing',
            name='year',
            field=models.SmallIntegerField(default=2015),
        ),
    ]
