# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_auto_20160210_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangement',
            name='signature',
            field=models.CharField(blank=True, default=b'', max_length=50, null=True),
        ),
    ]
