# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_auto_20160217_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursechoosing',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursechoosing',
            name='user',
        ),
        migrations.RemoveField(
            model_name='coursemessagenotice',
            name='msg',
        ),
        migrations.RemoveField(
            model_name='coursemessagenotice',
            name='target',
        ),
        migrations.RemoveField(
            model_name='coursemessage',
            name='author',
        ),
        migrations.AddField(
            model_name='coursemessage',
            name='deadline',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='CourseChoosing',
        ),
        migrations.DeleteModel(
            name='CourseMessageNotice',
        ),
    ]
