# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_perference_language'),
        ('education', '0005_auto_20160218_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('handle', models.CharField(blank=True, max_length=255, null=True)),
                ('max_size', models.IntegerField(default=1073741824)),
                ('cur_size', models.IntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.User')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='repositories',
            field=models.ManyToManyField(blank=True, to='education.Repository'),
        ),
    ]
