# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-28 05:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_auto_20160226_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
    ]
