# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_remove_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='handle',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
