# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-15 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_auto_20160303_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='EduMajor',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('short_id', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=50)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.EduDepartment')),
            ],
        ),
    ]
