# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-16 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='client',
            name='grant_type',
        ),
        migrations.RemoveField(
            model_name='client',
            name='response_type',
        ),
        migrations.RemoveField(
            model_name='client',
            name='scopes',
        ),
        migrations.AddField(
            model_name='client',
            name='appname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='avatar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
