# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-16 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20160709_1051'),
        ('oauth2', '0002_auto_20160716_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAllowClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_allow', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth2.Client')),
            ],
        ),
    ]
