# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-17 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0003_userallowclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='userallowclient',
            name='open_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
