# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asgn',
            name='remark',
            field=models.TextField(blank=True, default=b'', null=True),
        ),
    ]
