# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_auto_20160217_1244'),
        ('account', '0002_user_perference_language'),
        ('asgn', '0002_auto_20160210_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsgnVisitRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.SmallIntegerField(default=0)),
                ('create_time', models.IntegerField(default=0)),
                ('proc_time', models.IntegerField(default=0)),
                ('arrangement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.Arrangement')),
            ],
        ),
        migrations.RemoveField(
            model_name='asgn',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='asgnproblems',
            name='ignore_flag',
        ),
        migrations.RemoveField(
            model_name='stureport',
            name='deadline_time',
        ),
        migrations.AddField(
            model_name='asgnvisitrequirement',
            name='asgn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asgn.Asgn'),
        ),
        migrations.AddField(
            model_name='asgnvisitrequirement',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.User'),
        ),
    ]
