# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-18 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgn', '0003_auto_20160217_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asgn',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
