# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-23 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgn', '0005_auto_20160222_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='asgn',
            name='rank_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asgn',
            name='rank_list_cache_time',
            field=models.IntegerField(default=0),
        ),
    ]
