# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-06 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_auto_20160303_1055'),
        ('asgn', '0006_auto_20160223_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsgnAccessControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.IntegerField(default=0)),
                ('end_time', models.IntegerField(default=0)),
                ('enabled', models.BooleanField(default=False)),
                ('arrangement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.Arrangement')),
            ],
        ),
        migrations.RemoveField(
            model_name='asgn',
            name='arrangement',
        ),
        migrations.RemoveField(
            model_name='asgn',
            name='arrangement_setting',
        ),
        migrations.AddField(
            model_name='asgn',
            name='access_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asgn.AsgnAccessControl'),
        ),
    ]
