# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-06 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asgn', '0007_auto_20160706_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asgn',
            name='access_control',
        ),
        migrations.AddField(
            model_name='asgn',
            name='access_control',
            field=models.ManyToManyField(blank=True, to='asgn.AsgnAccessControl'),
        ),
    ]
