# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.SmallIntegerField(default=0)),
                ('sex', models.SmallIntegerField(default=-1)),
                ('realname', models.CharField(blank=True, max_length=50, null=True)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('motto', models.CharField(blank=True, max_length=255, null=True)),
                ('create_time', models.IntegerField(default=0)),
                ('email_validated', models.BooleanField(default=False)),
                ('email_findpwd_validated', models.CharField(blank=True, max_length=100, null=True)),
                ('logined_token', models.CharField(blank=True, max_length=100, null=True)),
                ('logined_token_expire', models.IntegerField(default=0)),
                ('login_pwd_retry_counter', models.SmallIntegerField(default=5)),
                ('visited', models.IntegerField(default=0)),
                ('solved', models.IntegerField(default=0)),
                ('submissions', models.IntegerField(default=0)),
                ('accepted', models.IntegerField(default=0)),
                ('spc_problem_publish', models.BooleanField(default=False)),
                ('spc_problem_viewer', models.BooleanField(default=False)),
            ],
        ),
    ]
