# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-13 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='perference_language',
            field=models.CharField(default=b'gcc', max_length=10),
        ),
    ]
