# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_perference_bgimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='perference_bgimg',
            new_name='preference_bgimg',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='perference_language',
            new_name='preference_language',
        ),
    ]
