# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-10 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20160308_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preference_problem_detail_mode',
            field=models.BooleanField(default=True),
        ),
    ]
