# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-18 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_headimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
