# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-09 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='point_login',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='point_solved',
            field=models.IntegerField(default=0),
        ),
    ]
